# Generated by Django 4.2.2 on 2023-11-01 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0011_cart_details_id_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout_detail',
            name='State',
        ),
    ]
