# Generated by Django 4.2.2 on 2023-11-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0012_remove_checkout_detail_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_detail',
            name='State',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
